### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by p4ntek**

### CODE REVIEW

**Comment by cyphunk** [comment]
thanks! <3
I added an ifdef for the esp_task_wdt.h include and changed the white space use a little.

**Comment by p4ntek** [comment]
> thanks! <3 I added an ifdef for the esp_task_wdt.h include and changed the white space use a little.
Thx too.
Not sure if esp32 have default watchdog timer but ive added for sure :)
Also please link update to my issue and close it if possible.
There is a my comment in pinout:
// nano esp32 - not sure if correct pinout
you can change it to example:
// pins for nano esp32

**Comment by cyphunk** [comment]
liking to the issue sounds like a smart idea. How do I do that? do I have to make a new commit or unwind or something/

peace

**Comment by p4ntek** [comment]
I've read instruction on github. Ill try(code):

Closes #24

**Pull request merged**
